# Generated by Django 5.2 on 2025-08-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_projectvideo'),
    ]

    operations = [
    ]
