# Generated by Django 5.2 on 2025-08-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20250813_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvideo',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional description for the video', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which videos appear (0 = first)'),
        ),
    ]
