# Generated by Django 5.2 on 2025-10-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_projectvideo_caption_alter_projectvideo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvideo',
            name='compressed_size_mb',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='original_size_mb',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='projectvideo',
            name='was_compressed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
