# Generated by Django 5.2 on 2025-10-27 07:55

import projects.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_projectvideo_compressed_size_mb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvideo',
            name='compression_quality',
            field=models.CharField(choices=[('high', 'High Quality (1080p)'), ('medium', 'Balanced (720p)'), ('low', 'Fast Upload (480p)')], default='medium', help_text='Quality preset for automatic compression (only used if file > 100MB)', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='video',
            field=projects.fields.CompressedVideoField(max_length=255, verbose_name='video'),
        ),
    ]
