# Generated by Django 5.2 on 2025-10-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_projectvideo_compression_quality_and_more'),
    ]

    operations = [
    ]
