# Generated by Django 5.2 on 2025-10-27 10:59

import cloudinary.models
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20251027_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectembed',
            name='is_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='projectphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[projects.models.ProjectPhoto.validate_image_file], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='projectvideo',
            name='compression_quality',
            field=models.CharField(choices=[('high', 'High Quality (1080p)'), ('medium', 'Balanced (720p)'), ('low', 'Fast Upload (480p)')], default='high', help_text='Quality preset for automatic compression (only used if file > 100MB)', max_length=10),
        ),
    ]
