# Generated by Django 5.2 on 2025-12-16 06:22

import django.db.models.deletion
from django.db import migrations, models


def create_categories_and_migrate_data(apps, schema_editor):
    """Create Category objects from existing category values and link them"""
    Projects = apps.get_model('projects', 'Projects')
    Category = apps.get_model('projects', 'Category')
    
    # Get all unique category values from existing projects
    existing_categories = Projects.objects.values_list('category', flat=True).distinct()
    
    # Create Category objects for each unique category
    category_map = {}
    for cat_name in existing_categories:
        if cat_name:  # Skip None/empty values
            category, created = Category.objects.get_or_create(name=cat_name)
            category_map[cat_name] = category
    
    # Update all projects with temp field (we'll do this in next migration)
    for project in Projects.objects.all():
        if project.category and project.category in category_map:
            # Store the category object ID in a temp field for now
            project.temp_category_id = category_map[project.category].id
            project.save(update_fields=['temp_category_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_projectembed_is_safe_alter_projectphoto_image_and_more'),
    ]

    operations = [
        # Step 1: Create Category model
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        # Step 2: Add temporary field to store category FK
        migrations.AddField(
            model_name='projects',
            name='temp_category_id',
            field=models.IntegerField(null=True, blank=True),
        ),
        # Step 3: Populate categories and temp field
        migrations.RunPython(create_categories_and_migrate_data, migrations.RunPython.noop),
        # Step 4: Remove old category field
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
        # Step 5: Add new category ForeignKey field
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ForeignKey(
                blank=True, 
                help_text='Select a category or add a new one in the Category section.', 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                to='projects.category'
            ),
        ),
    ]
