# Generated by Django 5.2 on 2025-12-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_tag_remove_projects_tags_projects_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
