# Generated by Django 5.2 on 2026-01-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_remove_projects_tags_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, help_text="Optional: e.g., 'Languages', 'Frameworks', 'Design Tools'", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='projects',
            name='technologies',
        ),
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=models.ManyToManyField(blank=True, help_text='Select technologies used in this project. Add new ones in the Technology section.', to='projects.technology'),
        ),
    ]
