# Generated by Django 5.2 on 2026-07-21 10:10

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_projects_display_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('teaser', models.CharField(help_text='One-line summary shown on the collapsed card.', max_length=200)),
                ('body', models.TextField(help_text='Full section content. Supports the same markdown as the article body.')),
                ('takeaways_raw', models.TextField(blank=True, help_text='Key takeaway bullet points, one per line. Leave blank to omit.', verbose_name='Takeaways')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('visual_placeholder', models.CharField(blank=True, help_text='Placeholder text shown in a dashed box where a diagram/animation will go later.', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='projects.projects')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
